//from uri in sdm-key
@cmisuri = https://api-sdm-di.cfapps.us10.hana.ondemand.com

//from uaa/clientid in sdm-key

@cmisclientid = sb-2e8b6804-a5f7-45b1-a664-8576e312f62c!b38660|sdm-di-DocumentManagement-sdm_integration!b6332

//from uaa/clientsecret in sdm-key

@cmisclientsecret = 2b60ce72-a114-44ed-bdcf-34e9755ab444$QagAUY9HOuwg5OJ6l7c_ealFUZeSKi0Qf9uyYkNcKho=
@cmistokenurl = https://dpeapps.authentication.us10.hana.ondemand.com


# @name getToken
POST {{cmistokenurl}}/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{cmisclientid}}:{{cmisclientsecret}}

client_id={{cmisclientid}}
&grant_type=client_credentials

###

# @name createRepository
@authToken = {{getToken.response.body.access_token}}
POST {{cmisuri}}/rest/v2/repositories HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

	{
		"repository": {
			"displayName": "freightorderattach",
			"description": "freightorderattach",
			"repositoryType": "internal",
			"isVersionEnabled":"false",
			"isVirusScanEnabled":"false",
			"skipVirusScanForLargeFile": "false",
			"isThumbnailEnabled": "false",
			"isEncryptionEnabled": "false",
			"isClientCacheEnabled": "false",
			"hashAlgorithms":"SHA-256",
			"isContentBridgeEnabled" : "false" 
			}
	}



###

# @name getRepository
@authToken = {{getToken.response.body.access_token}}
GET {{cmisuri}}/browser HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

# @name delRepository
@authToken = {{getToken.response.body.access_token}}
DELETE  {{cmisuri}}/browser/zfoattachment008 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

# @name testfunction
GET  http://localhost:4004/odata/v4/freightorder/SrvFreightOrder(TransportationOrderUUID='fa163ea1-6a76-1fe0-9694-2855aa39719f',IsActiveEntity=true)/suggestBestRoute()
Content-Type: application/json







